name = "ReducedOrderModelsProject"
uuid = "4abeecc2-dd9b-448a-92b8-8b1c39dced5b"
authors = ["Alec Hoyland <alec.hoyland@posteo.net>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
